category page
justinrusso/loot-locker pull request #68
Opened 2022-01-13 16:24 UTC by isaacsungpak

2022-01-13 17:37 UTC, andyrose507 approved these changes

2022-01-13 17:46 UTC, justinrusso requested changes

2022-01-13 17:46 UTC, justinrusso commented on react-app/src/components/search/Results.js
> +        setCategoryId(query.get("category") ? query.get("category") : undefined);
This should not be needed. If you want to set a default value for state when the component is first created you can pass the value directly into the state's initialization. Shift the `query` initialization above your `categoryId` state initialization and then you can pass `query.get('category') || ''` into the `useState` for `categoryId`

As a note, controlled inputs cannot have an undefined state. Perhaps (as I suggest above) you can set it to `''` when there is no category chosen?

2022-01-13 17:47 UTC, justinrusso commented on react-app/src/components/search/Results.js
> +        setCategoryId(query.get("category") ? query.get("category") : undefined);
@isaacsungpak I see this was just changed in https://github.com/justinrusso/loot-locker/pull/68/commits/a3468c738c8a5cb81fe973f56efdb76312006033 before I posted this. Take note of my mention of the value of the controlled input though. That still applies.

2022-01-14 21:25 UTC, justinrusso approved these changes

2022-01-14 21:25 UTC, merged